apiVersion: apps/v1
kind: Deployment
metadata:
  name: hola-deployment
spec:
  selector:
    matchLabels:
      app: hola
  replicas: 1
  template:
    metadata:
      labels:
        app: hola
    spec:
      containers:
      - name: hola
        image: ludinnento/hola:latest
        ports:
        - containerPort: 8080