version: '3'
services:
  myapp:
    build: .
    ports:
      - 8080:8080
    command: ./apps
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
